doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        schema_filter: ~^(?!(rm_)|(location))~
        types:
            uuid:
                class: App\Core\Infrastructure\DoctrineType\UuidIdentifierType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            TicTacToeGame:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/TicTacToeGame/mapping'
                prefix: 'App\Entity\TicTacToeGame'
                alias: TicTacToeGame
            TicTacToeMove:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/TicTacToeMove/mapping'
                prefix: 'App\Entity\TicTacToeMove'
                alias: TicTacToeMove
            LicitationGame:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/LicitationGame/mapping'
                prefix: 'App\Entity\LicitationGame'
                alias: LicitationGame
            LicitationMove:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/LicitationMove/mapping'
                prefix: 'App\Entity\LicitationMove'
                alias: LicitationMove
            LicitationAnswer:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/LicitationAnswer/mapping'
                prefix: 'App\Entity\LicitationAnswer'
                alias: LicitationAnswer
            LicitationItem:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/LicitationItem/mapping'
                prefix: 'App\Entity\LicitationItem'
                alias: LicitationItem
            LicitationPlayer:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/LicitationPlayer/mapping'
                prefix: 'App\Entity\LicitationPlayer'
                alias: LicitationPlayer

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
