version: "3.9"

networks:
  magisterka:

volumes:
  magisterka-db:

services:
  magisterka-api:
    container_name: magisterka-api
    build:
      context: .
      dockerfile: ./docker/magisterka-api/Dockerfile
    volumes:
      - .:/var/www/symfony/
      - ./docker/magisterka-api/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9001:9000"
    networks:
      - magisterka
    environment:
      - PHP_IDE_CONFIG=serverName=xdebug
    extra_hosts:
      - host.docker.internal:host-gateway

  magisterka-api-nginx:
    image: nginx:latest
    container_name: magisterka-api-nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/symfony/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - magisterka-api
    networks:
      - magisterka

  magisterka-database:
    image: postgres:14.3-alpine
    container_name: magisterka-database
    environment:
      POSTGRES_DB: magisterka-db
      POSTGRES_PASSWORD: magisterka
      POSTGRES_USER: magisterka
    ports:
      - "5432:5432"
    networks:
      - magisterka
    volumes:
      - magisterka-db:/var/lib/postgresql/data:rw
